version: "3"

services:
  db:
    image: postgres:12  
    container_name: db  
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: Telebot    
    restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DBPORT: 5432
      DBHOST: db
      DBNAME: Telebot
      DBUSER: postgres
      DBPASSWORD: postgres
    depends_on:
      - db